name: 🚀 Déploiement FTP Automatique

on:
  push:
    branches:
      - main  # Le script se lance à chaque push sur la branche main

jobs:
  web-deploy:
    name: 🚚 Sync Files to OVH
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: www/newsite/
        exclude: |
          **/.git*
          **/.git*/**
          **/.github*/**
          **/.DS_Store
          *.py
          Dockerfile
          .dockerignore
          files_to_update.txt
          nav_header.txt
          docs/**
          data/**
          export_ads_site.zip
          *.md
